[docker]
url = "http://127.0.0.1:2375"

[[docker.configs]]
image = "selenium/node-chrome:136.0-chromedriver-136.0-grid-4.38.0-20251101"
browserName = "chrome"

[[docker.configs]]
image = "selenium/node-firefox:144.0-geckodriver-0.36-grid-4.38.0-20251101"
browserName = "firefox"
