version: "3"

services:
  selenium-hub: 
    image: selenium/hub:4.34.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:137.0-chromedriver-137.0-grid-4.34.0-20250727
    container_name: chrome-node
    shm_size: 2gb
    depends_on: 
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
    networks:
      - selenium-grid

  # chrome-132:
  #   image: selenium/node-chrome:132.0-chromedriver-132.0-grid-4.34.0-20250727
  #   container_name: chrome-node-version-132
  #   shm_size: 2gb
  #   depends_on: 
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #     - VNC_NO_PASSWORD=1
  #   networks:
  #     - selenium-grid

  firefox:
    image: selenium/node-firefox:136.0.4-geckodriver-0.36.0-grid-4.34.0-20250717
    container_name: firefox-node
    shm_size: 2gb
    depends_on: 
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
    networks:
      - selenium-grid

networks:
  selenium-grid:
